### ISSUE TITLE
Настроить запуск unit-тестов через GitHub actions

### ISSUE THREAD

**Issue by leonid-konovalov** [cmf-team/pricer#12]
Запуск тестов должен происходить при 
* push в ветку master 
* при pull requirest в ветку master, 

При push в остальные ветки пока не нужно.

Нужна установка библиотек из файла requirements.txt.
Версия Python - 3.10.

https://www.youtube.com/watch?v=NijFSs03Pd4

**Comment by leonid-konovalov** [comment]
Можно как-то потестить что получается не делая коммитов в ветку master?

**Comment by epogrebnyak** [comment]
Что у вас на локале запускает тест, какая команда?

**Comment by epogrebnyak** [comment]
А где сами тесты - в каком-то бранче?

**Comment by leonid-konovalov** [comment]
В том же бранче, что и тестируемый код, конечно. Пример модуля с тестом:

https://github.com/cmf-team/pricer/blob/1-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%80%D0%B0%D1%81%D1%87%D0%B5%D1%82-%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B5%D0%B9-%D0%BF%D0%BE-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%83-%D1%81-%D0%B7%D0%B0%D1%89%D0%B8%D1%82%D0%BE%D0%B9-%D0%BA%D0%B0%D0%BF%D0%B8%D1%82%D0%B0%D0%BB%D0%B0/Implementation/Products/VanillaStructuredProductTest.py

**Comment by epogrebnyak** [comment]
Рекомендация - файлы назвать test_*.py классы Test_*, тогда их видит pytest

**Comment by epogrebnyak** [comment]
https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#conventions-for-python-test-discovery

**Comment by epogrebnyak** [comment]
При упаковке в пакет у вас код живёт отдельно, тесты в отдельной папке, но можно пока как есть, в одной папке

**Comment by leonid-konovalov** [comment]
Евгений, у нас эти моменты уже прописаны в guidelines

**Comment by epogrebnyak** [comment]
Я видел, рекомендуется поменять - вариант сейчас выбран экзотический. В гайдлайнах часть вещей выбрана хорошо, часть opinionated, but ok, часть можно автоматизировать, а часть себе создаёт сложностей, названия тестов - как раз из этой части. 

Вы чем руководствовались когда структуру названий придумывали?

**Comment by pacifikus** [comment]
Я сделала fork репозитория, чтобы пока здесь в master не коммитить.
Файл с запуском проверок - [check.yml](https://github.com/pacifikus/pricer/blob/master/.github/workflows/checks.yml)
[Отработавший пайплайн при PR](https://github.com/pacifikus/pricer/actions/runs/3200189383/jobs/5226801934)
[Отработавший пайплайн при Push](https://github.com/pacifikus/pricer/actions/runs/3200219754/jobs/5226864984)

**Comment by leonid-konovalov** [comment]
Хочу опробовать замкоммить что-нибудь нехорошее в fork, посмотреть что будет. Можете выдать мне права?



![Image](https://user-images.githubusercontent.com/74711923/194522062-9aa42744-3da9-40a6-9a63-d5291b2c2980.png)

**Comment by leonid-konovalov** [comment]
Приходит такое уведомление:


![Image](https://user-images.githubusercontent.com/74711923/194587796-c9913674-e0f1-4569-a3f9-e0015461d024.png)

**Comment by leonid-konovalov** [comment]
По-моему можно все переносить в основной репозиторий.
