### ISSUE TITLE
Исправить расчет платежей при наличии cap для структурного продукта "С защитой капитала"

### ISSUE THREAD

**Issue by leonid-konovalov** [cmf-team/pricer#33]
При расчете payoff cap не должен умножаться на participation. Нужно поправить реализацию и тесты.

![Image](https://user-images.githubusercontent.com/74711923/196410215-b9e56eaf-bb76-460b-b89a-d84ff7c27b8a.png)

https://www.six-structured-products.com/en/know-how/product-know-how/capital-protection-products/capital-protection-with-participation

![Image](https://user-images.githubusercontent.com/74711923/196410643-7be8a401-de9e-49b0-a016-af6a7c6765bf.png)

**Comment by pacifikus** [comment]
Посмотрите, пожалуйста, изменения в [последнем merge-коммите](https://github.com/cmf-team/pricer/commit/633eb665ea95fe84642022498594d95832beb393#diff-6bb1b34d0fad790559b728346ef2ee88ae7029ee217c4a4b9350dc040bbb599f). Если все хорошо, то можно будет закрыть ветку

**Comment by leonid-konovalov** [comment]
Если approved, а не request changes, то можно сразу удалять ветку.

**Comment by leonid-konovalov** [comment]
Выглядит все верно.

**Comment by leonid-konovalov** [comment]
Выглядит все верно.
