### ISSUE TITLE
Реализовать расчет базовой цены продукта "С защитой капитала"

### ISSUE THREAD

**Issue by leonid-konovalov** [cmf-team/pricer#8]
* Стоимость опционной части должна рассчитываться по формуле вида
B(0,T)*(F(t,T)N(d_1) - KN(d_2))
d_1,2=(ln⁡((F(t,T))/K)±(σ^2 T)/2)/(σ√T)
* F(t,T) считаем по формуле S(t)/B(t,T), где B(t,T) - фактор дисконтирования.
* Метод getTotalCovariance в классе CovarianceTermStructure возвращает σ√T для заданной даты (maturityDate опциона).
* Pricer в пакете Products - абстрактный класс (обозначается курсивом), нужно это поправить.
* Нужно реализовать методы класса SimulationPricer за исключением getCashFlowBasePrice
* Нужно реализовать метода setPricerCreator в классе Derivative и метод getBasePrice в классе VanillaStructuredProduct
* Для расчета ожидаемых значений в тестах можно использовать online-калькуляторы, например https://goodcalculators.com/black-scholes-calculator/. 
* В тестах нужно сделать stubs для классов CovarianceTermStructure и DiscountCurve.
* В классе VanillaStructuredProduct нужно реализовать метод getBasePrice.

**Comment by pacifikus** [comment]
@leonid-konovalov 
В процессе реализации возникло несколько вопросов:
- в классе `SimulationPricer `метод `getDiscountFactor `должен возвращать фактор дисконтирования. Как я понимаю, это подразумевает вызов `DiscountCurve.getDiscountFactor(paymentDate)`, однако в атрибутах класса `self.__drift` имеет тип `List[DiscountCurve]`, и не совсем понятно, какой конкретно элемент списка `self.__drift` должен выбираться? Видимо, тот у которого `valuationDate `совпадает с `SimulationPricer.__valuationDate`? Тогда, может быть для поиска удобнее вместо `List[DiscountCurve]` использовать `Dict[DiscountCurve]`?
- метод `SimulationPricer.getValuationDate()` должен просто возвращать `self.__valuationDate`?
- метод абстрактного класса `Derivative.setPricerCreator()` помечен как static, не вполне понятно, как тогда будет происходить set, если в методе нет референса на cls или self?

**Comment by leonid-konovalov** [comment]
1. Это ошибка, поправил.
2. Да.
3. Есть ассоциация. Она статическая, это означает что должен быть соответствующий атрибут класса (по умолчанию видимость private).
<img width="802" alt="image" src="https://user-images.githubusercontent.com/74711923/195859914-a8d3e2b7-dd36-4c43-b105-0253aa5eef15.png">
4. Класс Simulation и соответствующий атрибут пока делать не нужно, это будет метод Monte-Carlo.

**Comment by pacifikus** [comment]
А реализация метода `setPricerCreator `предполагается в `Derivative`?

```
class Derivative(PriceableElement, ABC):
    def __init__(self):
        self.pricer = None

    def setPricerCreator(self, newPricerCreator: PricerFactory):
        self.pricer = newPricerCreator.createPricer()
```
 если так, то не совсем понятно, откуда брать параметры для `newPricerCreator.createPricer`

**Comment by leonid-konovalov** [comment]
Если коротко, то это будет делать специальный класс, когда мы начнем пользоваться системой целиком.
Полный ответ здесь:
https://martinfowler.com/articles/injection.html

В рамках данной задачи этим методом пользоваться не нужно, но реализацию можно сделать.

**Comment by leonid-konovalov** [comment]
Как обычно, после закрытия задачи нужно удалить ветку.
